// =====================================================================
// Pluggable Storage — local filesystem or S3/MinIO, chosen by config
//
// KEY DECISION: downloads ALWAYS go through the API (GET /files/:id),
// never via a presigned URL handed to the client.
//
// Why: presigned URLs exist only in S3. If the API returns a presigned
// URL on S3 and a different mechanism on local disk, every consumer has
// to handle two cases, permission checks bypass the app on one path but
// not the other, and audit logging of file access becomes impossible on
// S3. Serving through the API makes the two drivers behaviourally
// identical and keeps `file:read` permission enforcement in one place.
//
// Cost: file bytes pass through the app server. At 25 concurrent users
// and ~20 GB/year this is irrelevant. Revisit only if it ever isn't.
// =====================================================================

import { Readable } from 'node:stream';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, unlink, stat } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { pipeline } from 'node:stream/promises';
import { randomUUID } from 'node:crypto';

// ---------------------------------------------------------------------
// 1. The interface — four methods. Keep it this small.
// ---------------------------------------------------------------------

export interface StorageDriver {
  readonly name: 'local' | 's3';
  put(key: string, body: Buffer | Readable, meta: PutMeta): Promise<void>;
  getStream(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  healthCheck(): Promise<boolean>;
}

export interface PutMeta {
  mime: string;
  size?: number;
  originalName?: string;
}

// ---------------------------------------------------------------------
// 2. Key generation and validation
//
// The object key is generated by US, never derived from the uploaded
// filename. A filename like "../../etc/passwd" or "../../../backup.dump"
// must never be able to influence a path. The original name is stored in
// the `file` table for display only.
// ---------------------------------------------------------------------

export function buildObjectKey(tenantId: string, mime: string): string {
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
  const ext = extensionFor(mime);
  return `${tenantId}/${yyyy}/${mm}/${randomUUID()}${ext}`;
}

const MIME_EXT: Record<string, string> = {
  'image/jpeg': '.jpg',
  'image/png': '.png',
  'image/webp': '.webp',
  'application/pdf': '.pdf',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': '.xlsx',
};
function extensionFor(mime: string): string {
  return MIME_EXT[mime] ?? '.bin';
}

/**
 * Defence in depth. Even though keys are generated, anything read back
 * from the database and used as a path is validated before it touches
 * the filesystem. A corrupted or tampered `object_key` row must not
 * become an arbitrary file read.
 */
export function assertSafeKey(key: string): void {
  if (!key || key.length > 512) throw new Error('INVALID_OBJECT_KEY');
  if (key.startsWith('/') || key.startsWith('\\')) throw new Error('INVALID_OBJECT_KEY');
  if (/^[a-zA-Z]:/.test(key)) throw new Error('INVALID_OBJECT_KEY');   // C:\...
  if (key.includes('\0')) throw new Error('INVALID_OBJECT_KEY');
  // reject any traversal segment, in either slash style
  for (const segment of key.split(/[/\\]/)) {
    if (segment === '..' || segment === '.') throw new Error('INVALID_OBJECT_KEY');
  }
  if (!/^[A-Za-z0-9._\-/]+$/.test(key)) throw new Error('INVALID_OBJECT_KEY');
}

// ---------------------------------------------------------------------
// 3. Local filesystem driver
// ---------------------------------------------------------------------

export class LocalStorageDriver implements StorageDriver {
  readonly name = 'local' as const;
  private readonly root: string;

  constructor(rootDir: string) {
    this.root = resolve(rootDir);
  }

  /** resolve + verify the result is still inside root — the real guard */
  private pathFor(key: string): string {
    assertSafeKey(key);
    const full = resolve(join(this.root, key));
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new Error('INVALID_OBJECT_KEY');
    }
    return full;
  }

  async put(key: string, body: Buffer | Readable): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    // write to a temp file then rename: a crash mid-write must not leave
    // a half-written file that looks valid to a later read
    const tmp = `${path}.${randomUUID()}.tmp`;
    if (Buffer.isBuffer(body)) {
      await pipeline(Readable.from(body), createWriteStream(tmp));
    } else {
      await pipeline(body, createWriteStream(tmp));
    }
    const { rename } = await import('node:fs/promises');
    await rename(tmp, path);
  }

  async getStream(key: string): Promise<Readable> {
    const path = this.pathFor(key);
    await stat(path);                      // throws ENOENT -> mapped to NOT_FOUND
    return createReadStream(path);
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.pathFor(key));
    } catch (e: any) {
      if (e.code !== 'ENOENT') throw e;    // deleting a missing file is a no-op
    }
  }

  async exists(key: string): Promise<boolean> {
    try { await stat(this.pathFor(key)); return true; }
    catch { return false; }
  }

  async healthCheck(): Promise<boolean> {
    try {
      await mkdir(this.root, { recursive: true });
      const probe = join(this.root, '.healthcheck');
      await pipeline(Readable.from(Buffer.from('ok')), createWriteStream(probe));
      await unlink(probe);
      return true;
    } catch { return false; }
  }
}

// ---------------------------------------------------------------------
// 4. S3 / MinIO driver
// ---------------------------------------------------------------------

import {
  S3Client, PutObjectCommand, GetObjectCommand,
  DeleteObjectCommand, HeadObjectCommand, HeadBucketCommand,
} from '@aws-sdk/client-s3';

export interface S3Config {
  endpoint?: string;          // set for MinIO, omit for real AWS
  region: string;
  bucket: string;
  accessKey: string;
  secretKey: string;
  forcePathStyle?: boolean;   // true for MinIO
}

export class S3StorageDriver implements StorageDriver {
  readonly name = 's3' as const;
  private readonly client: S3Client;

  constructor(private readonly cfg: S3Config) {
    this.client = new S3Client({
      endpoint: cfg.endpoint,
      region: cfg.region,
      credentials: { accessKeyId: cfg.accessKey, secretAccessKey: cfg.secretKey },
      forcePathStyle: cfg.forcePathStyle ?? Boolean(cfg.endpoint),
    });
  }

  async put(key: string, body: Buffer | Readable, meta: PutMeta): Promise<void> {
    assertSafeKey(key);
    await this.client.send(new PutObjectCommand({
      Bucket: this.cfg.bucket,
      Key: key,
      Body: body,
      ContentType: meta.mime,
      ContentLength: meta.size,
    }));
  }

  async getStream(key: string): Promise<Readable> {
    assertSafeKey(key);
    const res = await this.client.send(new GetObjectCommand({
      Bucket: this.cfg.bucket, Key: key,
    }));
    return res.Body as Readable;
  }

  async delete(key: string): Promise<void> {
    assertSafeKey(key);
    await this.client.send(new DeleteObjectCommand({
      Bucket: this.cfg.bucket, Key: key,
    }));
  }

  async exists(key: string): Promise<boolean> {
    assertSafeKey(key);
    try {
      await this.client.send(new HeadObjectCommand({ Bucket: this.cfg.bucket, Key: key }));
      return true;
    } catch { return false; }
  }

  async healthCheck(): Promise<boolean> {
    try {
      await this.client.send(new HeadBucketCommand({ Bucket: this.cfg.bucket }));
      return true;
    } catch { return false; }
  }
}

// ---------------------------------------------------------------------
// 5. NestJS wiring — one token, driver chosen at boot
// ---------------------------------------------------------------------

import { Module, Global } from '@nestjs/common';

export const STORAGE = Symbol('STORAGE');

@Global()
@Module({
  providers: [{
    provide: STORAGE,
    useFactory: (): StorageDriver => {
      const driver = process.env.STORAGE_DRIVER ?? 'local';

      if (driver === 's3') {
        for (const k of ['S3_BUCKET', 'S3_ACCESS_KEY', 'S3_SECRET_KEY']) {
          if (!process.env[k]) throw new Error(`STORAGE_DRIVER=s3 but ${k} is not set`);
        }
        return new S3StorageDriver({
          endpoint: process.env.S3_ENDPOINT,
          region: process.env.S3_REGION ?? 'us-east-1',
          bucket: process.env.S3_BUCKET!,
          accessKey: process.env.S3_ACCESS_KEY!,
          secretKey: process.env.S3_SECRET_KEY!,
          forcePathStyle: process.env.S3_FORCE_PATH_STYLE === 'true',
        });
      }

      if (driver === 'local') {
        return new LocalStorageDriver(process.env.STORAGE_LOCAL_PATH ?? '/data/files');
      }

      throw new Error(`Unknown STORAGE_DRIVER: ${driver}`);
    },
  }],
  exports: [STORAGE],
})
export class StorageModule {}

// Boot must fail loudly on misconfiguration. A server that starts with
// STORAGE_DRIVER=s3 and no credentials will accept uploads and lose them.
// Call healthCheck() during startup and refuse to listen if it fails.

// ---------------------------------------------------------------------
// 6. The single download path — identical for both drivers
// ---------------------------------------------------------------------

/*
@Get('files/:id')
@RequirePermissions('file:read')
async download(@Param('id') id: string, @Auth() ctx: AuthContext, @Res() res: Response) {
  const file = await this.files.findForTenant(id, ctx.tenantId);   // tenant-scoped
  if (!file) throw new NotFoundException('NOT_FOUND');

  await this.acl.assertCanReadEntity(ctx, file.entityType, file.entityId);
  await this.audit.log(ctx, 'file.download', 'file', file.id);

  res.setHeader('Content-Type', file.mimeType);
  res.setHeader('Content-Disposition',
    `attachment; filename="${encodeURIComponent(file.originalName)}"`);
  res.setHeader('X-Content-Type-Options', 'nosniff');

  const stream = await this.storage.getStream(file.objectKey);
  stream.pipe(res);
}
*/

// Note the two checks before any byte is read: the file row must belong
// to the caller's tenant, AND the caller must be permitted to read the
// entity the file is attached to. A medical scan attached to a child is
// readable only by someone who can read that child's medical record.
