import { Readable } from 'node:stream';
import { randomUUID } from 'node:crypto';

/**
 * Pluggable storage — local filesystem or S3/MinIO, chosen by
 * STORAGE_DRIVER (kindergarten-docs/src/storage.ts). Downloads always go
 * through GET /files/:id, never a presigned URL — that's what keeps
 * `file:read` permission enforcement and audit logging in one place
 * regardless of which driver is active.
 */
export interface StorageDriver {
  readonly name: 'local' | 's3';
  put(key: string, body: Buffer | Readable, meta: PutMeta): Promise<void>;
  getStream(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  healthCheck(): Promise<boolean>;
}

export interface PutMeta {
  mime: string;
  size?: number;
  originalName?: string;
}

const MIME_EXT: Record<string, string> = {
  'image/jpeg': '.jpg',
  'image/png': '.png',
  'image/webp': '.webp',
  'application/pdf': '.pdf',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': '.xlsx',
};
function extensionFor(mime: string): string {
  return MIME_EXT[mime] ?? '.bin';
}

/**
 * The object key is generated by us, never derived from the uploaded
 * filename — "../../etc/passwd" must never be able to influence a path.
 * The original name is stored in the `file` table for display only.
 */
export function buildObjectKey(tenantId: string, mime: string): string {
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
  const ext = extensionFor(mime);
  return `${tenantId}/${yyyy}/${mm}/${randomUUID()}${ext}`;
}

/**
 * Defence in depth. Even though keys are generated, anything read back
 * from the database and used as a path is validated before it touches
 * the filesystem — a corrupted or tampered object_key row must not
 * become an arbitrary file read.
 */
export function assertSafeKey(key: string): void {
  if (!key || key.length > 512) throw new Error('INVALID_OBJECT_KEY');
  if (key.startsWith('/') || key.startsWith('\\')) throw new Error('INVALID_OBJECT_KEY');
  if (/^[a-zA-Z]:/.test(key)) throw new Error('INVALID_OBJECT_KEY'); // C:\...
  if (key.includes('\0')) throw new Error('INVALID_OBJECT_KEY');
  for (const segment of key.split(/[/\\]/)) {
    if (segment === '..' || segment === '.') throw new Error('INVALID_OBJECT_KEY');
  }
  if (!/^[A-Za-z0-9._\-/]+$/.test(key)) throw new Error('INVALID_OBJECT_KEY');
}
